### ISSUE TITLE
How to set up language for map and autocomplete form?

### ISSUE THREAD

**Issue by alexanderkon** [sgruhier/typeahead-addresspicker#10]
Hi
How to set up language for map and autocomplete form?
thanks

**Comment by davidtaubmann** [comment]
You can force the language to be used in all maps API by specifying it in the script.

Here's where I found the solution:
http://stackoverflow.com/a/28130182/1920145

Basically, add _&language=YourLanguageAbrv_ at the end of the URL of the script
