### ISSUE TITLE
Support latest typeahead

### ISSUE THREAD

**Issue by RHavar** [sgruhier/typeahead-addresspicker#32]
Love your picker, but it seems to only works with typeahead 0.10.x and not 0.11.x, unfortunately

**Comment by sgruhier** [comment]
Correct
I checked 0.11.x and the change A LOT the Bloodhound API :(
I need to check doc (and code!) of this new version.

Any help is welcome ! :)

From the Changelog


An overhaul of typeahead.js – consider this a release candidate for v1. There are bunch of API changes with this release so don't expect backwards compatibility with previous versions. There are also many new undocumented features that have been introduced. Documentation for those features will be added before v1 ships.

Beware that since this release is pretty much a rewrite, there are bound to be some bugs. To be safe, you should consider this release beta software and throughly test your integration of it before using it in production environments. This caveat only applies to this release as subsequent releases will address any issues that come up.

**Comment by canfiax** [comment]
+1

GREAT plugin but we really need support for 0.11.x

**Comment by canfiax** [comment]
@sgruhier any idea when you should extend for support for latest typeahead? It would greatly improve this package, and grant you additional downloads.

I don't think it would take more than a few hours to build.

**Comment by sgruhier** [comment]
I'm pretty busy these days 
unfortunately, I cannot give you an estimated date :(

**Comment by WinnieK** [comment]
Any success on that? Would be much appreciated

**Comment by chrispecher** [comment]
I managed find a way to get the addresspicker to work with the latest typeahead and bloodhound (0.11.1). It's a bit hacky, but saved my day.

The 'get' function of bloodhound has changed and we need to use 'search' instead. So in the addresspicker file replace 

``` javascript
AddressPicker.prototype.get = function(query, cb) {
```

with

``` javascript
AddressPicker.prototype.search = function(query, sync, async) {
```

and in the that function replace

``` javascript
return cb(predictions);
```

with

``` javascript
return async(predictions);
```

One problem remains. The async callback is only called, if a remote option is specified for the bloodhound base class. So when instantiating the address picker just add a fake remote option.

``` javascript
var addressPicker = new AddressPicker({
   remote: 'fakeRemote'
});
```

**Comment by thomasa1980** [comment]
any chance you guys know how to change the address format in both the suggestions and the results?  I would like to remove the country and add the postal_code.  I already restricted suggestions to US only.

**Comment by marcofugaro** [comment]
please make it work for lastest version, a lot of things have changed in 0.11 typehead.

Addresspicker doesn't even fires up.

**Comment by Shaker-Hamdi** [comment]
It would be really great if you can support latest version of typeahead, there's a lot of issues with backward compatibility.

**Comment by manumora** [comment]
Thank you @Zumpo !!! It works!

**Comment by thomasbrodusch** [comment]
@Zumpo I've trying to fix it with your code (change the .get function in AddressPicker file).
Geocoding works very well but the addresspicker never shows up the autocomplete suggestion in the typeahead dropdown menu (?!)

Sample of my own code:

```
addressPickerObject = new AddressPicker({
     remote: 'fakeRemote'
 });


   // add the custom addressPicker event to the form
  addressPickerObject.bindDefaultTypeaheadEvent($(config.addressPickerDiv));


 $(config.addressPickerDiv).typeahead(null,{
      displayKey: 'description',
      source: addressPickerObject//.ttAdapter()
});
```

Any ideas ?

**Comment by Kopyov** [comment]
@sgruhier Sébastien, please take a look at this update when you have time, this extension is very helpful, but it doesn't work with the latest versions of dependencies.

Thanks

**Comment by sgruhier** [comment]
Sorry I was so busy
I'll try to give a look today or before the end of that week

**Comment by sgruhier** [comment]
I puhsed a typeahead-0.11.1 branch
You'll have to add a limit options

``` js
    $('#address1').typeahead(null, {
      displayKey: 'description',
      limit: 20,
      source: addressPicker
    });
```

I don't know exactly why. I'll try to figure it out.
I'm not happy also when you type the selection panel blinks (quick hide and show) If someone has an idea :)

Any feedback are welcome.

**Comment by jellis** [comment]
I'm guessing something to do with

```
that._append(query, suggestions.slice(0, that.limit - rendered));
```

Which is on line 1724 of the typeahead-bundle.js file.

Excellent work on this. Just outstanding. Thanks so much for your efforts.

**Comment by sgruhier** [comment]
Yes, I don't understand yet that part of the code 'that.limit - rendered'
