### ISSUE TITLE
Question: Can I call somehow the updateMap function based on an address that I have? 

### ISSUE THREAD

**Issue by rmagnum2002** [sgruhier/typeahead-addresspicker#34]
Let's say I have  an address in a field that is written there by a js code, not by user, that means no type-ahead drop-down will appear and no select event will be fired to geocode the address.

Is there any way to trigger the geocode event and make it do the same as if a user would select an address from the drop-down?

Thank you.

**Comment by rmagnum2002** [comment]
solved it, thank you

**Comment by Adam-78** [comment]
@rmagnum2002 how did you manage to retrigger the typeahead to update map user manually updates an address field e.g the postcode? I am trying to do something similar. Any help would be appreciated.

**Comment by rmagnum2002** [comment]
@Adam-78 my case was different from what you need, in my case I was updating the value of the field that is used as input for addresspicker and based on it's value I wanted to display the marker on proper position. What you want is to update the map based on inputs that are used only to fill in the results from gmaps... in other words, it's either you use the typeahead input to retrieve address information or you can drag the marker.. typing in other fields something won't update the map, that's my understanding.
You might want to open a new issue/request on this repository and maybe some of the contributors might help you.
