### ISSUE TITLE
why some places is not suggested as autocompleteService 

### ISSUE THREAD

**Issue by buncismamen** [sgruhier/typeahead-addresspicker#37]
why when I write place, some place it not shown for autocomplete,
but when I try to write it in maps.google.com, google have autocomplete for that place
is typeahead-addresspicker use different autocompleteService?
can I use the autocomplete that maps.google.com have?

so I have do some research
and i found it theres is two type autocomplete that google have
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform
there is type parameter in googleautocomplete the first one use all and the second one is 'geocode'

It seems typeahead use the second one
I assume that because the resullt that the second one give
is same as when I use typeahead addresspicker

**Comment by mohd-saqib** [comment]
having the same issue .what if i want to use getQueryPredictions() instead of getPlacePredictions() ?
