### ISSUE TITLE
getting the address back on the form

### ISSUE THREAD

**Issue by thomasa1980** [sgruhier/typeahead-addresspicker#41]
I don't know what I'm doing wrong and I'm positive someone has a simple answer to this but I'm having trouble receiving the address on the form submission.  I moved the address field inside the form but it didn't help.  When inspecting the form I see the address is actually in some overlaid fields of some sort but I do not see a field name that I can reference in my script.

any insight is appreciated.

**Comment by thomasa1980** [comment]
I'm able to pull lat/lon but not address info.  

This is what I'm using (I used the type names defined by the google maps API): 

```
$(addressPicker).on('addresspicker:selected', function (event, result) {
    $('#lat').val(result.lat());
    $('#lon').val(result.lng());
    $('#street1').val(str.concat(result.nameForType('street_number'),' ',result.nameForType('route')));
    $('#city').val(result.nameForType('locality'));
    $('#state').val(result.nameForType('administrative_area_level_1'));
    $('#zip').val(result.nameForType('postal_code'));
});
```

**Comment by thomasa1980** [comment]
got it figured out, it was a script error in how I used concat that threw the whole thing...

side note @sgruhier how do I get the short name?  i.e. How do I get PA instead of Pennsylvania?

**Comment by thomasa1980** [comment]
man, I can't believe how simple that second question was.... 

just add true in order to return the google short_name...:
$('#state').val(result.nameForType('administrative_area_level_1', true));

**Comment by sgruhier** [comment]
Happy you fix you issue by yourself !
