### ISSUE TITLE
Autocomplete Not working on Angular 7 

### ISSUE THREAD

**Issue by parveenladaf** [sgruhier/typeahead-addresspicker#64]
I am following the same step in javascript the autocomplete is working.
but when I am using the same in angular 7 it Not working.

**Comment by parveenladaf** [comment]
can someone help me to solve this issue in angular 7

**Comment by parveenladaf** [comment]
solved!

**Comment by sgruhier** [comment]
great, if you can share your problem and how you fixed it, that would be great
